### ISSUE TITLE
Solve for autostarting imperative containers

### ISSUE THREAD

**Issue by m1cr0man** [m1cr0man/python-nixos-nspawn#8]
Due to NixOS' nature, imperative containers do not autostart at boot. We need to work out a solution for this in order for imperative containers to be viable in a production environment.

A [systemd unit generator](https://www.freedesktop.org/software/systemd/man/systemd.generator.html) may be required.

**Comment by eldritch-cookie** [comment]
why can't we just `machinectl enable` the containers?

**Comment by m1cr0man** [comment]
The problem is that on NixOS, the relevant parts of the filesystem are readonly and/or declaratively defined. Example invokation:

```
[lucas@unimog:~/nix-configs]$ sudo machinectl enable web
Failed to enable or disable unit: File /etc/systemd/system/multi-user.target.wants/machines.target: Read-only file system
```

Some experimentation needs to be done but maybe we can use `environment.etc` to link machines.target to somewhere writable and that may suffice, or a more complex solution may need to be found depending on how the systemd NixOS modules define their paths.

**Comment by m1cr0man** [comment]
This is done now! Oh... damn. I did not realize it's been a year. Time flies when IRL gets busy..

This is implemented as a subcommand on nixos-nspawn, starting with [this commit](https://github.com/m1cr0man/python-nixos-nspawn/commit/201340c5762947809b221e970f7dff94e9439552). On NixOS, the hypervisor module will, by default, set up a systemd service which runs the autostart command and subsequently starts all the containers.
